#!/usr/bin/env bash
# factors challenge

check_factor() {
    num1=$2
    num2=$3
    if [ "$num2" -gt "$num1" ]; then
        # Swap num1 and num2 if num2 is greater
        tmp=$num1
        num1=$num2
        num2=$tmp
    fi
    echo "$1=$num1*$num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
else
    while read -r i; do
        result=$(factor "$i" | sed 's/.*: //')
        IFS=' ' read -ra factors <<< "$result"
        check_factor "$i" "${factors[@]}"
    done < "$1"
fi

